cmake_minimum_required(VERSION 3.16)


set(BSP_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../BSP)
set(COMPONENTS_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../components)
set(THIRDPARTY_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../thirdparty)
set(UITILITY_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../utility)
set(FLASH_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../flash)
set(BOOTLOADER_ROOT_PATH ${CMAKE_CURRENT_LIST_DIR}/../bootloader)
